name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of artifact files
        required: true
        default: dist
        type: string
    outputs:
      anyNameOfResult:
        description: Result of operation
        value: ${{ jobs.deploy.outputs.outcomeXXX}} # outcomeXXX - goes from *1
jobs:
  deploy:
    outputs:
      outcomeXXX: ${{ steps.set-result.outputs.step-resultQQQ}} # *1
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output info
        run: echo "Deploying & uploading..."
      - name: Set Result output
        id: set-result
        run: echo "step-resultQQQ=success" >> $GITHUB_OUTPUT